### ISSUE TITLE
C'est cassé ?

### ISSUE THREAD

**Issue by ElieDeloumeau** [HugoGresse/kaamelott-bot#13]
Bonjour,

Le bot n'est plus fonctionnel ? J'ai une erreur `/kaamelott failed with the error "dispatch_failed"`

D'avance merci,
Élie

**Comment by HugoGresse** [comment]
Coucou, je l'avais hébergé sur mon NAS mais le service à sauté, je peux le remettre en route si besoin !

**Comment by ElieDeloumeau** [comment]
Ça serait super, c'est une fonctionnalité critique et nécessaire au bon fonctionnement de tout bon Slack qui se respecte

**Comment by HugoGresse** [comment]
C'est bon!
